### ISSUE TITLE
Animate label when focused.

### ISSUE THREAD

**Issue by nirleshem** [kishanraja/FloatingLabelTextFieldSwiftUI#11]
Hi,
Would be great to have the option to animate the label as soon as the textfield is focused, rather than when the user starts typing.

Like shown in the material components site:
https://material-ui.com/components/text-fields/ 

Much Appreciated.

**Comment by kishanraja** [comment]
Hello, @nirleshem Thank You for this suggestion. I have added new properties ```.enablePlaceholderOnFocus(true)```. Please update the library.
