### ISSUE TITLE
Remove/conditionally import references to UIKit to allow macOS support?

### ISSUE THREAD

**Issue by TheGeekPharaoh** [kishanraja/FloatingLabelTextFieldSwiftUI#12]
I haven't dug into the internals of the code yet, but would it be possible to add support for conditionally importing any references to UIKit?  As it stands, the references to UIKit are preventing this library from being used in macOS SwiftUI applications.

**Comment by kishanraja** [comment]
Hello @TheGeekPharaoh 
Currently this library, not support by mac OS as we need some UIKit reference. Also, adding conditions will not work. In the future will possible.

**Comment by TheGeekPharaoh** [comment]
The Package.swift file still indicates that macOS is supported.  This should likely be removed.
