### ISSUE TITLE
How To Remove The Bottom Line 

### ISSUE THREAD

**Issue by rahat14** [kishanraja/FloatingLabelTextFieldSwiftUI#14]
How to remove the bottom horizontal line ?

**Comment by kishanraja** [comment]
Hello, @rahat14, For now, there is no property for hiding/ remove the bottom line but you can set the following property to hide a line.
```
.lineHeight(0)
.selectedLineHeight(0)
```

**Comment by ImaginativeShohag** [comment]
Line is no disappear. :(
