### ISSUE TITLE
Placeholder problem with .enablePlaceholderOnFocus

### ISSUE THREAD

**Issue by karasahinemre** [kishanraja/FloatingLabelTextFieldSwiftUI#15]
When .enablePlaceholderOnFocus set to "true" there are some UI errors at the end of focusing.

<img width="362" alt="Screen Shot 2021-05-05 at 10 42 43" src="https://user-images.githubusercontent.com/9135318/117110347-a4655e00-ad8e-11eb-9b07-7f2e518c9beb.png">

**Comment by kishanraja** [comment]
Hello, @karasahinemre Thank you for reporting the issue. Issue fixed in the new version build.
