### ISSUE TITLE
When i blur out from a textfield . It show both placeholder and text at the same time

### ISSUE THREAD

**Issue by tylerlantern** [kishanraja/FloatingLabelTextFieldSwiftUI#16]
<img width="514" alt="Screenshot 2021-05-24 at 10 05 47" src="https://user-images.githubusercontent.com/5992573/119290981-de33d100-bc77-11eb-868c-b30b8ce5e85b.png">

**Comment by kishanraja** [comment]
@tylerlantern Thanks for reporting. Could you please add your code??

**Comment by tylerlantern** [comment]
It has been fixed in 4.2.1.
Thank
