### ISSUE TITLE
Argument of '#selector' does not refer to an '@objc' method, property, or initializer

### ISSUE THREAD

**Issue by daliborristic883** [kishanraja/FloatingLabelTextFieldSwiftUI#17]
I am getting compile error as like below.
![Screenshot 2021-05-28 at 1 36 00 PM](https://user-images.githubusercontent.com/65829381/119978219-a69b9080-bfb9-11eb-8932-3de6b6c8d627.png)

**Comment by kishanraja** [comment]
Seems like you have change this. Please refer this    ```  return #selector(UIResponderStandardEditActions.`self`) ```

https://github.com/kishanraja/FloatingLabelTextFieldSwiftUI/blob/b9aab8fa5f13474180274cfb7022357e8461b838/Sources/FloatingLabelTextFieldSwiftUI/Extensions/UITextField%2BExtension.swift#L22

**Comment by daliborristic883** [comment]
Ok thank you. @kishanraja
