### ISSUE TITLE
Issues with validation

### ISSUE THREAD

**Issue by bludginozzie** [kishanraja/FloatingLabelTextFieldSwiftUI#2]
Consider the following source code:

I have discovered a few issue with validation.

- When a field is required I cannot figure out how to display the error.  I am using the below code however the error message just flashes briefly.

```
   FloatingLabelTextField($username, validtionChecker: $isValidUsername, placeholder: "Username")
      .addValidation(.init(condition: !username.isEmpty, errorMessage: "Username is required"))
      .isShowError(true)
      .errorColor(.red)
      .frame(height: 50)
```

- Validation does not appear to work on SecureTextEntry fields.  In the below example `isValidPassword` is always false

```
FloatingLabelTextField($password, validtionChecker: $isValidPassword, placeholder: "Password")
   .addValidation(.init(condition: !password.isEmpty, errorMessage: "Password is required"))
   .isShowError(true)
   .errorColor(.red)
   .isSecureTextEntry(!self.isPasswordShow)
   .frame(height: 50)
```

Any assistance would be appreciated

**Comment by kishanraja** [comment]
Thank you for reporting issues.
I have added new isRequired floating text field property in v4.0.1 for check whether field is required or not with error message.

**Comment by bludginozzie** [comment]
Thank you for fixing this issue.  I am using cocoapods and have updated to 4.0.1 however the change is not available.  Can you please check cocoapods for this fix.

**Comment by kishanraja** [comment]
> Thank you for fixing this issue. I am using cocoapods and have updated to 4.0.1 however the change is not available. Can you please check cocoapods for this fix.

I don't know why Cocoapods not update. some time I hate Cocoapods. I have release another version of pod it will take time to update pod. if possible then add manually code or use package manager.
