### ISSUE TITLE
Unable to set Input View

### ISSUE THREAD

**Issue by sumitchhangani** [kishanraja/FloatingLabelTextFieldSwiftUI#23]
how can I set input view with FloatingLabelTextField ? I wanted to display picker instead of keyboard ? but currently can't find a way to set input view.
let me know if there is a way.

**Comment by kishanraja** [comment]
You can’t even create picker view with SwiftUI TextField. In SwiftUI there is no any option like UITextField inputview. You can create picker by this way (https://www.hackingwithswift.com/quick-start/swiftui/how-to-create-a-picker-and-read-values-from-it). Another good option is to bind UIKit textfield object with SwiftUI or hide show SwiftUI picker view on begin and end closure method.
