### ISSUE TITLE
Keyboard type should not allow character and special symbols when type is Numberpad?

### ISSUE THREAD

**Issue by karthisiva** [kishanraja/FloatingLabelTextFieldSwiftUI#5]
I am creating mobile number field and setting keyboard type as **NumberPad**.  Then following scenario occurs:

When running with iPad keyboard we are able to enter special characters. (iPad only)
We can paste the text which is copied earlier(iPad and iPhone).
How to find out each and every character typed? **callbacks not calling**

I am able to do this without your library by reading this tutorial [https://programmingwithswift.com/numbers-only-textfield-with-swiftui/](url)

see image here:

![Screen Shot 2020-10-17 at 12 48 44 PM](https://user-images.githubusercontent.com/6926979/96331503-62d3c680-107b-11eb-9354-5b44364c1171.png)

I don"t have clear idea where to implement this in your class files. It would much better with those features.

Hope you got my points, Thanks for your great work.

**Comment by kishanraja** [comment]
Please refer to new version from v4.0.1
I have added a new property for disabling text field editing action.

 .addDisableEditingAction([.paste]) /// Disable text field editing action. Like cut, copy, past, all etc.

Thank you very much and sorry for my late response.
