### ISSUE TITLE
validtionChecker becomes TRUE only after closing the keyboard

### ISSUE THREAD

**Issue by ezamp** [kishanraja/FloatingLabelTextFieldSwiftUI#6]
I defined a FloatingLabelTextField (with var isValidMasterPwd2  as validtionChecker) whose content must be the same as the string inserted in another TextField. If I insert a string identical to the other in this TextField, the variable isValidMasterPwd2 becomes TRUE only after closing the keyboard.
Is there a way for the variable to immediately become TRUE as soon as the validity conditions are satisfied?

```
FloatingLabelTextField($masterPwd2, validtionChecker: $isValidMasterPwd2, 
placeholder: "Re-type Password", editingChanged: { (isChanged) in
                }) {
                }
                .isShowError(true)
                .addValidations([.init(condition: masterPwd1 == masterPwd2, errorMessage: "Password not equal")])
                .isRequiredField(true, with: "Password field is required")
                .isSecureTextEntry(!self.isMasterPwd2Show)
                .modifier(ThemeTextField())
```

**Comment by kishanraja** [comment]
Hello @ezamp ,
For some limitation from my side right now there is no any way for immediately become TRUE. I don't know why you need this but you can use this approch : 

Declare one computed variable like 

```
   var isPasswordMatch: Bool {
        password == password2
    }
```
and use isPasswordMatch variable as per your requirement.
